### ISSUE TITLE
What's the default quantization type?

### ISSUE THREAD

**Issue by liamsun2019** [alibaba/TinyNeuralNetwork#14]
Hi, I notice that the default value to parameter 'asymmetric' is True, which indicates that the quantization should be done as uint8. But the following codes make me a little confused:

if not self.asymmetric:                                                                                               
    sym_fq = torch_q.FakeQuantize.with_args(observer=torch_q.MovingAverageMinMaxObserver, quant_min=0, quant_max=255,
                                           dtype=torch.quint8, qscheme=torch.per_tensor_symmetric, reduce_range=False)
    qconfig = torch_q.QConfig(sym_fq, qconfig.weight)

where, even users set the 'asymmetric' to False, the codes still force to use uint8. Any suggestions? Thanks a lot.

**Comment by peterjc123** [comment]
> What's the default quantization type?
Asymmetric quantization, which uses `uint8` as the data type.

> where, even users set the 'asymmetric' to False, the codes still force to use uint8.
No, your understanding is not correct. Since we use the QNNPACK backend, the dtype of the weights are required to be of `uint8` type at the PyTorch side. What actually matters here is the argument `qscheme=torch.per_tensor_symmetric`, apart from the default value `torch.per_tensor_affine`, which means the offset is always pinned to `128`, while the scale remain learnable. Later, during the conversion phase, we will minus the unsigned quantized values (ranges from 0 to 256) by 128 so that they will become `int8`.

**Comment by liamsun2019** [comment]
I get it. Thanks a lot.

**Comment by liamsun2019** [comment]
I set asymmetric=False to TFLiteConverter and the generated tflite is int8 quantized then. Big thanks.
